runtime: python312

entrypoint: gunicorn --bind :$PORT -w 4 flask_file_accept:app

instance_class: F2

env_variables:
  BUCKET_NAME: "kupamanduk-scholar-bucket"
  GOOGLE_API_KEY: "AIzaSyAQCZ2bJHOI6yapnei35Eyrd2IL19ts9GM"

handlers:
  - url: /
    script: auto
  - url: /static
    static_dir: static
    