import random

from ThreadPool import ThreadPool, TaskStatus, TaskBase
from google_CSE_access import GoogleCSEAccess
from gcs_manager import GCSManager
import constants

import json

class JsonDataStore:
    def __init__(self, json_data_root_name: str):
        self.root_name = json_data_root_name
        self.data_store = {self.root_name: {}}
    
    def save_key(self, key: str, data):
        """Saves the key-data pair in the JSON root."""
        self.data_store[self.root_name][key] = data
    
    def read_key(self, key: str):
        """Reads the data for the given key from the JSON root and returns it."""
        return self.data_store[self.root_name].get(key, None)
    
    def get_json_string(self):
        """Returns the stored data as a JSON string."""
        return json.dumps(self.data_store, indent=2)
    
    def get_json_data(self):
        """Returns the stored data as a dictionary."""
        return self.data_store
    

    def update_from_json_data(self, json_data):
        """Update the internal JSON structure with a given JSON data struct."""
        if isinstance(json_data, dict) and self.root_name in json_data:
            self.data_store[self.root_name].update(json_data[self.root_name])

    def update_from_json_string(self, json_string: str):
        """Loads data from a JSON string."""
        try:
            loaded_data = json.loads(json_string)
            if self.root_name in loaded_data:
                self.data_store[self.root_name] = loaded_data[self.root_name]
        except json.JSONDecodeError:
            pass

class ContentCreatorTask(TaskBase):
    def __init__(self, section, gemini_access, error_manager):
        super().__init__()

        self.section = section

        self.gemini_access = gemini_access
        self.error_manager = error_manager

    def run(self):
        obj = ContentCreatorBase(self.section, self.gemini_access, self.error_manager)

        print(f"Generating content for section {self.section}")

        obj.generate_all_contents()
        obj.finish()

class ContentCreatorBase:
    def __init__(self, section, gemini_access, error_manager):

        self.section = section

        self.gemini_access = gemini_access
        self.error_manager = error_manager

        self.section_json_root_map = {
            "hindustani_classical_music": "hindustani_classical_music_json_root",
            "yoga": "yoga_json_root",
            "racing": "racing_json_root",
            "winter_sports": "winter_sports_json_root",
            "general_machines": "general_machines_json_root",
            "industrial_machines": "industrial_machines_json_root",
            "oscar_nominated_movies": "oscar_nominated_movies_json_root",
            "grammy_songs": "grammy_songs_json_root",
            "internal_organ": "internal_organ_json_root",
            "astronomy": "astronomy_json_root",
            "golf": "golf_json_root",
            "nutrition": "nutrition_json_root",
            "stocks": "stocks_json_root",
            "mutual_funds": "mutual_funds_json_root",
            "medical_care": "medical_care_json_root",
            "painting": "painting_json_root",
            "physics": "physics_json_root",
            "chemistry": "chemistry_json_root",
            "biology": "biology_json_root",
            "computer_science": "computer_science_json_root",
            "electronics": "electronics_json_root",
            "geography": "geography_json_root",
            "political_science": "political_science_json_root",
            "authors": "authors_json_root",
            "economics": "economics_json_root"
        }

        self.topic_list = {
            "hindustani_classical_music": 
                [
                "Yaman", "Bhairav", "Bhairavi", "Todi", "Marwa", "Kafi", 
                "Khamaj", "Darbari Kanada", "Desh", "Bageshree", 
                "Malhar", "Hamsadhwani", "Chakravakam", "Charukesi", 
                "Shankarabharanam", "Kalyani", "Kharaharapriya", "Natabhairavi", 
                "Puriya Dhanashree", "Miyan ki Todi", "Jaijaivanti", "Tilak Kamod",
                "Rageshree", "Ahir Bhairav", "Jog", "Madhuvanti", "Kirwani", 
                "Hemant", "Bihag", "Alhaiya Bilawal", "Shuddha Sarang",
                "Kamod", "Basant", "Miyan ki Malhar", "Gaud Malhar",
                "Patdeep", "Shivranjani", "Hansdhwani", "Durga", "Kalingada"
                ],
            "yoga":
                [
                "Tadasana (Mountain Pose)",
                "Vrikshasana (Tree Pose)",
                "Adho Mukha Svanasana (Downward Dog Pose)",
                "Uttanasana (Standing Forward Bend)",
                "Trikonasana (Triangle Pose)",
                "Virabhadrasana I (Warrior I Pose)",
                "Virabhadrasana II (Warrior II Pose)",
                "Virabhadrasana III (Warrior III Pose)",
                "Parivrtta Trikonasana (Revolved Triangle Pose)",
                "Utkatasana (Chair Pose)",
                "Bhujangasana (Cobra Pose)",
                "Dhanurasana (Bow Pose)",
                "Salabhasana (Locust Pose)",
                "Setu Bandhasana (Bridge Pose)",
                "Paschimottanasana (Seated Forward Bend)",
                "Janu Sirsasana (Head-to-Knee Pose)",
                "Ardha Matsyendrasana (Half Lord of the Fishes Pose)",
                "Padmasana (Lotus Pose)",
                "Sukhasana (Easy Pose)",
                "Balasana (Child's Pose)",
                "Matsyasana (Fish Pose)",
                "Halasana (Plow Pose)",
                "Sarvangasana (Shoulder Stand Pose)",
                "Sirsasana (Headstand Pose)",
                "Chaturanga Dandasana (Four-Limbed Staff Pose)",
                "Navasana (Boat Pose)",
                "Anjaneyasana (Low Lunge Pose)",
                "Bakasana (Crow Pose)",
                "Kapotasana (Pigeon Pose)",
                "Eka Pada Rajakapotasana (One-Legged King Pigeon Pose)",
                "Shavasana (Corpse Pose)"
                ],
            "internal_organ":
                [
                "Brain",
                "Spinal Cord",
                "Heart",
                "Lungs", 
                "Liver", 
                "Kidneys",
                "Spleen",
                "Pancreas",
                "Stomach",
                "Intestines", 
                "Small Intestine",
                "Large Intestine",
                "Gallbladder",
                "Bladder",
                "Endocrine Glands", 
                "Thyroid",
                "Pituitary Gland",
                "Adrenal Glands",
                "Musculoskeletal System", 
                "Bones",
                "Muscles",
                "Joints",
                "Immune System",
                "Lymphatic System",
                "Reproductive System",
                "Male Reproductive System",
                "Female Reproductive System"
                ],
            "astronomy":
                [
                    "Celestial Objects",
                    "Stars",
                    "Planets",
                    "Moons", 
                    "Comets", 
                    "Asteroids", 
                    "Meteors", 
                    "Galaxies", 
                    "Nebulae",
                    "Black Holes",
                    "Cosmology", 
                    "Big Bang Theory", 
                    "Dark Matter", 
                    "Dark Energy", 
                    "Stellar Evolution", 
                    "Star Formation", 
                    "Supernovae", 
                    "Stellar Remnants", 
                    "Planetary Systems", 
                    "Exoplanets", 
                    "Astrophysics", 
                    "Astrobiology", 
                    "Observational Astronomy", 
                    "Telescopes", 
                    "Space Exploration", 
                    "Spacecraft", 
                    "Missions to Other Planets", 
                    "History of Astronomy", 
                    "Famous Astronomers", 
                    "Astrophysics Concepts", 
                    "Relativity", 
                    "Quantum Mechanics", 
                    "Astrochemistry", 
                    "Space Weather", 
                    "Astrobiology" 
                ],
            "golf":
                [
                    "Golf Rules", 
                    "Etiquette", 
                    "Swing Techniques", 
                    "Driving", 
                    "Iron Play", 
                    "Short Game", 
                    "Chipping", 
                    "Pitching", 
                    "Putting", 
                    "Course Management", 
                    "Hazard Play", 
                    "Bunker Play", 
                    "Water Hazards", 
                    "Mental Game", 
                    "Focus and Concentration", 
                    "Pressure Handling", 
                    "Course Strategy", 
                    "Club Selection", 
                    "Shot Shaping", 
                    "Equipment", 
                    "Clubs", 
                    "Balls", 
                    "Golf Course Design", 
                    "History of Golf", 
                    "Famous Golfers", 
                    "Golf Tournaments", 
                    "PGA Tour", 
                    "LPGA Tour", 
                    "European Tour", 
                    "Golf Competitions", 
                    "Amateur Golf", 
                    "Professional Golf" 
                ],
            "nutrition":
                [
                    "Macronutrients", 
                    "Carbohydrates", 
                    "Proteins", 
                    "Fats", 
                    "Micronutrients", 
                    "Vitamins", 
                    "Minerals", 
                    "Nutrition and Health", 
                    "Weight Management", 
                    "Chronic Diseases", 
                    "Immune System", 
                    "Mental Health", 
                    "Digestive Health", 
                    "Sports Nutrition", 
                    "Special Populations", 
                    "Pregnancy and Lactation", 
                    "Childhood and Adolescence", 
                    "Older Adults", 
                    "Food Science and Safety", 
                    "Food Composition and Analysis", 
                    "Food Safety", 
                    "Food Labeling", 
                    "Nutrition and Society", 
                    "Food Security and Sustainability", 
                    "Public Health Nutrition", 
                    "Research and Methodology", 
                    "Nutritional Epidemiology", 
                    "Clinical Nutrition" 
                ],
            "mutual_funds":
                [
                    # Basic Concepts
                    "Introduction to Mutual Funds",
                    "Types of Mutual Funds",
                    "Open-ended vs Closed-ended Funds",
                    "Exchange-Traded Funds (ETFs)",
                    "Index Funds",
                    "Sector Funds",
                    "Equity Funds",
                    "Debt Funds",
                    "Hybrid Funds",
                    "Money Market Funds",

                    # Investment Strategies
                    "Systematic Investment Plan (SIP)",
                    "Systematic Withdrawal Plan (SWP)",
                    "Systematic Transfer Plan (STP)",
                    "Lump Sum Investment",
                    "Value Averaging Investment Strategy",

                    # Mutual Fund Structures
                    "Unit Trusts",
                    "Fund of Funds (FoFs)",
                    "Direct Plans vs Regular Plans",
                    "Growth Option vs Dividend Option",
                    "Dividend Reinvestment",

                    # Fund Management
                    "Asset Management Companies (AMCs)",
                    "Role of Fund Managers",
                    "Expense Ratios",
                    "Entry and Exit Loads",
                    "Net Asset Value (NAV)",
                    "Turnover Ratio",

                    # Risks and Returns
                    "Market Risk",
                    "Credit Risk",
                    "Interest Rate Risk",
                    "Liquidity Risk",
                    "Inflation Risk",
                    "Diversification Benefits",
                    "Compounding in Mutual Funds",
                    
                    # Performance Measurement
                    "Alpha and Beta",
                    "Sharpe Ratio",
                    "Treynor Ratio",
                    "Expense Ratio",
                    "Tracking Error",
                    "Standard Deviation",

                    # Regulatory and Legal Aspects
                    "Securities and Exchange Board of India (SEBI) Regulations",
                    "Mutual Fund Offer Document",
                    "Know Your Customer (KYC) Requirements",
                    "Tax Implications on Mutual Funds",
                    "Capital Gains Tax",
                    "Tax-Saving Mutual Funds (ELSS)",

                    # Mutual Fund Platforms
                    "Direct Investment Platforms",
                    "Robo-Advisors",
                    "Mutual Fund Distributors",
                    "Online Mutual Fund Portals",

                    # Research and Analysis
                    "Fund Ratings",
                    "Fund Comparison Tools",
                    "Portfolio Diversification",
                    "Historical Returns Analysis",
                    "Market Trends Impacting Mutual Funds",

                    # Advanced Topics
                    "Thematic Funds",
                    "International Mutual Funds",
                    "Smart Beta Funds",
                    "Dynamic Asset Allocation Funds",
                    "ESG (Environmental, Social, and Governance) Funds",

                    # Mutual Fund Exit Strategies
                    "Redeeming Mutual Fund Units",
                    "Switching Between Mutual Funds",
                    "Exit Load Considerations"
                ],
            "stocks":
                [
                    "Introduction to Stock Market",
                    "Types of Stocks (Common vs Preferred)",
                    "Stock Exchanges (NYSE, NASDAQ, BSE, NSE, etc.)",
                    "Primary Market vs Secondary Market",
                    "Stock Indices (S&P 500, Dow Jones, NIFTY 50, etc.)",
                    "Blue-Chip Stocks",
                    "Penny Stocks",
                    "Growth Stocks vs Value Stocks",
                    "Dividend Stocks",
                    "IPO (Initial Public Offering)",
                    "Stock Market Orders (Market Order, Limit Order, Stop-Loss Order, etc.)",
                    "Fundamental Analysis of Stocks",
                    "Technical Analysis of Stocks",
                    "Stock Valuation Methods (PE Ratio, PB Ratio, EV/EBITDA, etc.)",
                    "Stock Market Trends and Cycles",
                    "Bull Market vs Bear Market",
                    "Short Selling and Margin Trading",
                    "Stock Market Risks and Volatility",
                    "Sectoral Stocks (Technology, Healthcare, Finance, etc.)",
                    "Stock Splits and Reverse Splits",
                    "Market Capitalization (Large Cap, Mid Cap, Small Cap)",
                    "Stock Dividends and Buybacks",
                    "Day Trading vs Swing Trading vs Long-Term Investing",
                    "ETFs (Exchange-Traded Funds) vs Stocks",
                    "Stock Portfolio Diversification",
                    "Insider Trading and Market Regulations",
                    "Stock Market Psychology and Behavioral Finance",
                    "Derivatives (Options, Futures, etc.)",
                    "Cryptocurrency vs Stocks",
                    "Impact of Interest Rates on Stocks",
                    "Role of Central Banks in Stock Markets"
                ],
            "economics":
                [
                    # Microeconomics
                    "Demand and Supply",
                    "Elasticity of Demand and Supply",
                    "Consumer Behavior and Utility Theory",
                    "Market Structures (Perfect Competition, Monopoly, Oligopoly)",
                    "Game Theory and Strategic Behavior",
                    "Production and Costs",
                    "Labor Markets and Wages",
                    "Externalities and Market Failure",
                    "Public Goods and Free Rider Problem",
                    "Behavioral Economics",

                    # Macroeconomics
                    "Gross Domestic Product (GDP) and Economic Growth",
                    "Inflation and Deflation",
                    "Unemployment and Labor Market Dynamics",
                    "Fiscal Policy and Government Spending",
                    "Monetary Policy and Central Banks",
                    "Interest Rates and Money Supply",
                    "Business Cycles and Economic Recessions",
                    "International Trade and Balance of Payments",
                    "Exchange Rates and Currency Markets",
                    "National Debt and Deficit",

                    # Development Economics
                    "Poverty and Income Inequality",
                    "Human Development Index (HDI)",
                    "Economic Growth vs Economic Development",
                    "Sustainable Development",
                    "Foreign Aid and Economic Assistance",
                    "Microfinance and Financial Inclusion",
                    "Industrialization and Urbanization",

                    # International Economics
                    "Comparative Advantage and Trade Theories",
                    "Globalization and Trade Liberalization",
                    "WTO, IMF, and World Bank",
                    "Tariffs, Quotas, and Trade Barriers",
                    "Foreign Direct Investment (FDI)",
                    "Exchange Rate Systems (Fixed, Floating, Pegged)",
                    "Economic Integration (EU, NAFTA, ASEAN)",
                    "Currency Crises and Sovereign Debt",

                    # Financial Economics
                    "Stock Markets and Asset Pricing",
                    "Bonds and Interest Rate Determination",
                    "Risk and Uncertainty in Financial Markets",
                    "Financial Crises and Market Bubbles",
                    "Banking System and Financial Intermediation",
                    "Cryptocurrency and Decentralized Finance (DeFi)",

                    # Environmental & Resource Economics
                    "Climate Change and Economic Policy",
                    "Carbon Tax and Emissions Trading",
                    "Renewable vs Non-Renewable Resources",
                    "Sustainability and Green Economics",
                    "Natural Resource Management",

                    # Political Economy
                    "Capitalism vs Socialism vs Mixed Economy",
                    "Economic Systems and Government Intervention",
                    "Public Choice Theory",
                    "Economic Policies and Political Ideologies",
                    "Economic Consequences of War",

                    # Emerging Topics
                    "Digital Economy and E-Commerce",
                    "Gig Economy and Freelancing",
                    "Automation and AI in the Workforce",
                    "Universal Basic Income (UBI)",
                    "Future of Work and Remote Economy"
                ],
            "racing":
                [
                    # Types of Racing
                    "Formula 1 (F1)",
                    "MotoGP",
                    "NASCAR",
                    "IndyCar",
                    "Drag Racing",
                    "Rally Racing",
                    "Touring Car Racing",
                    "Endurance Racing (Le Mans, WEC)",
                    "Electric Racing (Formula E)",
                    "Kart Racing",
                    "Off-Road Racing (Baja, Dakar Rally)",
                    "Truck Racing",
                    "Snowmobile Racing",
                    "Boat Racing",
                    "Drone Racing",

                    # Racing Strategies & Techniques
                    "Overtaking Techniques",
                    "Racing Line and Cornering",
                    "Braking Techniques (Trail Braking, Threshold Braking)",
                    "Tire Management Strategies",
                    "Slipstreaming and Drafting",
                    "Fuel Management",
                    "Aerodynamics in Racing",
                    "Qualifying Strategies",

                    # Racing Cars & Motorcycles
                    "Aerodynamics in Race Cars",
                    "Engine Performance and Tuning",
                    "Hybrid and Electric Racing Cars",
                    "Chassis Design and Suspension Setup",
                    "Transmission and Gear Ratios",
                    "Tires and Tire Compounds",
                    "Weight Distribution and Balance",

                    # Famous Races and Championships
                    "Monaco Grand Prix (F1)",
                    "24 Hours of Le Mans",
                    "Daytona 500 (NASCAR)",
                    "Indianapolis 500 (IndyCar)",
                    "Dakar Rally",
                    "Isle of Man TT",
                    "Pikes Peak International Hill Climb",
                    "Bathurst 1000",
                    "Goodwood Festival of Speed",

                    # Racing Safety & Regulations
                    "Helmet and Fireproof Suit Regulations",
                    "HANS Device and Safety Innovations",
                    "FIA and Racing Rulebooks",
                    "Track Safety and Barriers",
                    "Pit Stop Safety Protocols",
                    "Race Flags and Their Meanings",
                    "Penalties and Race Steward Decisions",

                    # Racing Technology & Data Analysis
                    "Telemetrics and Car Data Analysis",
                    "Simulation and Racing Simulators",
                    "Virtual Racing and eSports (iRacing, Gran Turismo)",
                    "Wind Tunnel Testing",
                    "Driver Fitness and Training",

                    # Racing Legends & Teams
                    "Michael Schumacher",
                    "Ayrton Senna",
                    "Lewis Hamilton",
                    "Valentino Rossi",
                    "Dale Earnhardt",
                    "Sebastian Loeb",
                    "Famous Racing Teams (Ferrari, Red Bull Racing, Mercedes AMG, McLaren)",

                    # Business & Sponsorships in Racing
                    "Sponsorship and Advertising in Motorsport",
                    "Team Budgets and Financial Management",
                    "TV Rights and Media Coverage",
                    "Merchandising and Fan Engagement",
                    
                    # Future of Racing
                    "Autonomous Racing (RoboRace)",
                    "Sustainable Racing (Biofuels, Hydrogen, EVs)",
                    "AI in Racing Strategies",
                    "Virtual Reality in Racing Training"
                ],
            "winter_sports":
                [
                    # Ice-Based Sports
                    "Ice Hockey",
                    "Figure Skating",
                    "Speed Skating",
                    "Short Track Speed Skating",
                    "Curling",

                    # Snow-Based Sports
                    "Alpine Skiing",
                    "Cross-Country Skiing",
                    "Ski Jumping",
                    "Snowboarding",
                    "Freestyle Skiing",
                    "Nordic Combined",
                    "Biathlon",

                    # Sledding & Sliding Sports
                    "Bobsleigh",
                    "Luge",
                    "Skeleton",

                    # Extreme & Adventure Winter Sports
                    "Ice Climbing",
                    "Snowmobiling",
                    "Winter Triathlon",
                    "Backcountry Skiing",
                    "Snowshoeing"
                ],
            "industrial_machines":
                [
                    # Industrial Machines
                    "Lathe Machine",
                    "Milling Machine",
                    "CNC Machine",
                    "3D Printer",
                    "Drilling Machine",
                    "Grinding Machine",
                    "Injection Molding Machine",
                    "Press Machine",
                    "Welding Machine",

                    # Construction Machines
                    "Excavator",
                    "Bulldozer",
                    "Crane",
                    "Concrete Mixer",
                    "Road Roller",
                    "Forklift",
                    "Dump Truck",

                    # Automotive Machines
                    "Internal Combustion Engine",
                    "Electric Motor",
                    "Turbocharger",
                    "Transmission System",
                    "Car Suspension System",

                    # Agricultural Machines
                    "Tractor",
                    "Combine Harvester",
                    "Plow",
                    "Seeder",
                    "Irrigation Pump",

                    # Computing & Robotics
                    "Supercomputer",
                    "Quantum Computer",
                    "Autonomous Robot",
                    "3D Scanner",
                    "Industrial Robot Arm",

                    # Medical Machines
                    "MRI Machine",
                    "CT Scanner",
                    "X-ray Machine",
                    "Ultrasound Machine",
                    "Dialysis Machine",
                    "Ventilator",

                    # Aerospace Machines
                    "Jet Engine",
                    "Rocket Engine",
                    "Flight Simulator",
                    "Autopilot System",

                    # Energy Machines
                    "Wind Turbine",
                    "Hydroelectric Generator",
                    "Solar Panel",
                    "Nuclear Reactor",
                    "Steam Turbine"
                ],
            "general_machines":
                [
                    # Office Machines
                    "Printer",
                    "Scanner",
                    "Photocopier",
                    "Shredder",
                    "Laminating Machine",

                    # Household Machines
                    "Washing Machine",
                    "Refrigerator",
                    "Microwave Oven",
                    "Vacuum Cleaner",
                    "Dishwasher",

                    # Simple Machines
                    "Lever",
                    "Pulley",
                    "Wheel and Axle",
                    "Inclined Plane",
                    "Wedge",
                    "Screw"
                ],
            "oscar_nominated_movies":
                [
                    # 2024
                    "The Holdovers",
                    "Killers of the Flower Moon",
                    "Oppenheimer",
                    "Barbie",
                    "The Fabelmans",
                    "The Color Purple",
                    "Poor Things",
                    "The Bikeriders",
                    "American Fiction",
                    
                    # 2023
                    "Everything Everywhere All at Once",
                    "The Banshees of Inisherin",
                    "All Quiet on the Western Front",
                    "Avatar: The Way of Water",
                    "Top Gun: Maverick",
                    "Elvis",
                    "The Whale",
                    "Tár",
                    "Triangle of Sadness",
                    
                    # 2022
                    "CODA",
                    "The Power of the Dog",
                    "Dune",
                    "King Richard",
                    "Belfast",
                    "Licorice Pizza",
                    "Don't Look Up",
                    "Drive My Car",
                    "Nightmare Alley",
                    
                    # 2021
                    "Nomadland",
                    "The Trial of the Chicago 7",
                    "Mank",
                    "Promising Young Woman",
                    "Minari",
                    "Sound of Metal",
                    "Judas and the Black Messiah",
                    "The Father",
                    "A Promising Young Woman",
                    
                    # 2020
                    "Parasite",
                    "1917",
                    "Once Upon a Time in Hollywood",
                    "Jojo Rabbit",
                    "Little Women",
                    "Marriage Story",
                    "The Irishman",
                    "Ford v Ferrari",
                    "Joker",
                    
                    # 2019
                    "Green Book",
                    "A Star is Born",
                    "Roma",
                    "Black Panther",
                    "BlacKkKlansman",
                    "Vice",
                    "The Favourite",
                    "Bohemian Rhapsody",
                    "Green Book",
                    
                    # 2018
                    "The Shape of Water",
                    "Three Billboards Outside Ebbing, Missouri",
                    "Darkest Hour",
                    "Dunkirk",
                    "Phantom Thread",
                    "Call Me by Your Name",
                    "Lady Bird",
                    "The Post",
                    "Get Out",
                    
                    # 2017
                    "Moonlight",
                    "La La Land",
                    "Manchester by the Sea",
                    "Arrival",
                    "Hacksaw Ridge",
                    "Lion",
                    "Hidden Figures",
                    "Fences",
                    "Hell or High Water",
                    
                    # 2016
                    "Spotlight",
                    "The Revenant",
                    "The Big Short",
                    "Mad Max: Fury Road",
                    "Bridge of Spies",
                    "The Martian",
                    "Brooklyn",
                    "Room",
                    "Steve Jobs",
                    
                    # 2015
                    "Birdman",
                    "The Theory of Everything",
                    "Selma",
                    "The Imitation Game",
                    "Whiplash",
                    "American Sniper",
                    "Boyhood",
                    "The Grand Budapest Hotel",
                    "Foxcatcher",
                    
                    # 2014
                    "12 Years a Slave",
                    "Gravity",
                    "American Hustle",
                    "The Wolf of Wall Street",
                    "Captain Phillips",
                    "Dallas Buyers Club",
                    "Her",
                    "Nebraska",
                    "The Lego Movie",
                    
                    # 2013
                    "Argo",
                    "Les Misérables",
                    "Life of Pi",
                    "Lincoln",
                    "Silver Linings Playbook",
                    "Zero Dark Thirty",
                    "Django Unchained",
                    "Beasts of the Southern Wild",
                    "Amour",
                    
                    # 2012
                    "The Artist",
                    "Hugo",
                    "The Help",
                    "Moneyball",
                    "Midnight in Paris",
                    "The Tree of Life",
                    "War Horse",
                    "Extremely Loud & Incredibly Close",
                    "Bridesmaids",
                    
                    # 2011
                    "The King's Speech",
                    "The Social Network",
                    "Black Swan",
                    "Inception",
                    "The Fighter",
                    "127 Hours",
                    "Toy Story 3",
                    "True Grit",
                    "Winter's Bone",
                    
                    # 2010
                    "The Hurt Locker",
                    "Avatar",
                    "Inglourious Basterds",
                    "Precious",
                    "Up",
                    "District 9",
                    "Up in the Air",
                    "A Serious Man",
                    "An Education",
                    
                    # 2009
                    "Slumdog Millionaire",
                    "The Curious Case of Benjamin Button",
                    "Milk",
                    "The Reader",
                    "Frost/Nixon",
                    "The Wrestler",
                    "Frozen River",
                    "Inglourious Basterds",
                    "Star Trek",
                    
                    # 2008
                    "No Country for Old Men",
                    "There Will Be Blood",
                    "Atonement",
                    "Juno",
                    "Michael Clayton",
                    "Sweeney Todd",
                    "The Diving Bell and the Butterfly",
                    "Into the Wild",
                    "Elizabeth: The Golden Age",
                    
                    # 2007
                    "The Departed",
                    "Letters from Iwo Jima",
                    "The Queen",
                    "Babel",
                    "The Pursuit of Happyness",
                    "Little Miss Sunshine",
                    "The Prestige",
                    "Dreamgirls",
                    "The Lives of Others",
                    
                    # 2006
                    "Crash",
                    "Brokeback Mountain",
                    "Capote",
                    "Good Night, and Good Luck",
                    "Munich",
                    "The Constant Gardener",
                    "Syriana",
                    "Walk the Line",
                    "King Kong",
                    
                    # 2005
                    "Million Dollar Baby",
                    "The Aviator",
                    "Ray",
                    "Sideways",
                    "Finding Neverland",
                    "Hotel Rwanda",
                    "The Incredibles",
                    "The Polar Express",
                    "Kinsey",
                    
                    # 2004
                    "The Lord of the Rings: The Return of the King",
                    "Lost in Translation",
                    "Master and Commander",
                    "Mystic River",
                    "Seabiscuit",
                    "Cold Mountain",
                    "The Last Samurai",
                    "The Cooler",
                    "The Big Fish",
                    
                    # 2003
                    "Chicago",
                    "The Pianist",
                    "The Hours",
                    "Lord of the Rings: The Two Towers",
                    "Gangs of New York",
                    "The Good Girl",
                    "Catch Me If You Can",
                    "The Lord of the Rings: The Fellowship of the Ring",
                    "The Lord of the Rings: The Fellowship",
                    
                    # 2002
                    "A Beautiful Mind",
                    "Moulin Rouge!",
                    "Black Hawk Down",
                    "Gosford Park",
                    "The Lord of the Rings: The Fellowship of the Ring",
                ],
            "grammy_songs":
                [
                    # 2023
                    "Just Like That - Bonnie Raitt",
                    "About Damn Time - Lizzo",
                    "The Heart Part 5 - Kendrick Lamar",
                    "Easy on Me - Adele",
                    "Bad Habit - Steve Lacy",
                    "As It Was - Harry Styles",
                    "Break My Soul - Beyoncé",
                    "God Did - DJ Khaled ft. Rick Ross, Lil Wayne, Jay-Z, John Legend, and Fridayy",
                    "ABCDEFU - GAYLE",
                    "All Too Well (10 Minute Version) - Taylor Swift",

                    # 2022
                    "Leave the Door Open - Silk Sonic (Bruno Mars & Anderson .Paak)",
                    "drivers license - Olivia Rodrigo",
                    "Happier Than Ever - Billie Eilish",
                    "Kiss Me More - Doja Cat ft. SZA",
                    "Peaches - Justin Bieber ft. Daniel Caesar & Giveon",
                    "Right on Time - Brandi Carlile",
                    "Montero (Call Me By Your Name) - Lil Nas X",
                    "Bad Habits - Ed Sheeran",
                    "A Beautiful Noise - Alicia Keys & Brandi Carlile",
                    "Fight for You - H.E.R.",

                    # 2021
                    "I Can't Breathe - H.E.R.",
                    "Black Parade - Beyoncé",
                    "The Box - Roddy Ricch",
                    "Cardigan - Taylor Swift",
                    "Circles - Post Malone",
                    "Don't Start Now - Dua Lipa",
                    "Everything I Wanted - Billie Eilish",
                    "If the World Was Ending - JP Saxe ft. Julia Michaels",

                    # 2020
                    "Bad Guy - Billie Eilish",
                    "Always Remember Us This Way - Lady Gaga",
                    "Bring My Flowers Now - Tanya Tucker",
                    "Hard Place - H.E.R.",
                    "Lover - Taylor Swift",
                    "Norman F***ing Rockwell - Lana Del Rey",
                    "Someone You Loved - Lewis Capaldi",
                    "Truth Hurts - Lizzo",

                    # 2019
                    "This Is America - Childish Gambino",
                    "All the Stars - Kendrick Lamar & SZA",
                    "Boo'd Up - Ella Mai",
                    "God's Plan - Drake",
                    "In My Blood - Shawn Mendes",
                    "The Joke - Brandi Carlile",
                    "The Middle - Zedd, Maren Morris & Grey",
                    "Shallow - Lady Gaga & Bradley Cooper",

                    # 2018
                    "That's What I Like - Bruno Mars",
                    "Despacito - Luis Fonsi & Daddy Yankee ft. Justin Bieber",
                    "4:44 - Jay-Z",
                    "Issues - Julia Michaels",
                    "1-800-273-8255 - Logic ft. Alessia Cara & Khalid",
                    "Praying - Kesha",
                    "Broken Halos - Chris Stapleton",
                    "Stay - Zedd & Alessia Cara",

                    # 2017
                    "Hello - Adele",
                    "Formation - Beyoncé",
                    "I Took a Pill in Ibiza - Mike Posner",
                    "Love Yourself - Justin Bieber",
                    "7 Years - Lukas Graham",

                    # 2016
                    "Thinking Out Loud - Ed Sheeran",
                    "Alright - Kendrick Lamar",
                    "Blank Space - Taylor Swift",
                    "Girl Crush - Little Big Town",
                    "See You Again - Wiz Khalifa ft. Charlie Puth",

                    # 2015
                    "Stay with Me (Darkchild Version) - Sam Smith",
                    "All About That Bass - Meghan Trainor",
                    "Chandelier - Sia",
                    "Shake It Off - Taylor Swift",
                    "Take Me to Church - Hozier",

                    # 2014
                    "Royals - Lorde",
                    "Just Give Me a Reason - Pink ft. Nate Ruess",
                    "Locked Out of Heaven - Bruno Mars",
                    "Roar - Katy Perry",
                    "Same Love - Macklemore & Ryan Lewis ft. Mary Lambert",

                    # 2013
                    "We Are Young - Fun. ft. Janelle Monáe",
                    "Adorn - Miguel",
                    "Call Me Maybe - Carly Rae Jepsen",
                    "Stronger (What Doesn't Kill You) - Kelly Clarkson",
                    "The A Team - Ed Sheeran",

                    # 2012
                    "Rolling in the Deep - Adele",
                    "All of the Lights - Kanye West, Rihanna, Kid Cudi & Fergie",
                    "The Cave - Mumford & Sons",
                    "Grenade - Bruno Mars",
                    "Holocene - Bon Iver",

                    # 2011
                    "Need You Now - Lady Antebellum",
                    "Beg Steal or Borrow - Ray LaMontagne",
                    "F*** You - CeeLo Green",
                    "The House That Built Me - Miranda Lambert",
                    "Love the Way You Lie - Eminem ft. Rihanna",

                    # 2010
                    "Single Ladies (Put a Ring on It) - Beyoncé",
                    "Poker Face - Lady Gaga",
                    "Pretty Wings - Maxwell",
                    "Use Somebody - Kings of Leon",
                    "You Belong with Me - Taylor Swift",

                    # 2009
                    "Viva la Vida - Coldplay",
                    "American Boy - Estelle ft. Kanye West",
                    "Chasing Pavements - Adele",
                    "I'm Yours - Jason Mraz",
                    "Love Song - Sara Bareilles",

                    # 2008
                    "Rehab - Amy Winehouse",
                    "Before He Cheats - Carrie Underwood",
                    "Hey There Delilah - Plain White T's",
                    "Like a Star - Corinne Bailey Rae",
                    "Umbrella - Rihanna ft. Jay-Z",

                    # 2007
                    "Not Ready to Make Nice - Dixie Chicks",
                    "Be Without You - Mary J. Blige",
                    "Jesus, Take the Wheel - Carrie Underwood",
                    "Put Your Records On - Corinne Bailey Rae",
                    "You're Beautiful - James Blunt",

                    # 2006
                    "Sometimes You Can't Make It on Your Own - U2",
                    "Bless the Broken Road - Rascal Flatts",
                    "Devils & Dust - Bruce Springsteen",
                    "Ordinary People - John Legend",
                    "We Belong Together - Mariah Carey",

                    # 2005
                    "Daughters - John Mayer",
                    "If I Ain't Got You - Alicia Keys",
                    "Jesus Walks - Kanye West"
                ],
            "medical_care":
                [
                    "Primary Care",
                    "Preventive Care",
                    "Emergency Care",
                    "Acute Care",
                    "Chronic Disease Management",
                    "Surgical Care",
                    "Specialist Consultations",
                    "Maternity Care",
                    "Pediatrics",
                    "Cardiology",
                    "Oncology",
                    "Orthopedics",
                    "Dermatology",
                    "Neurology",
                    "Endocrinology",
                    "Gastroenterology",
                    "Nephrology",
                    "Rheumatology",
                    "Pulmonology",
                    "Urology",
                    "Ophthalmology (Eye Care)",
                    "Otolaryngology (ENT)",
                    "Mental Health and Psychiatry",
                    "Rehabilitation Services",
                    "Physical Therapy",
                    "Occupational Therapy",
                    "Pharmacy Services",
                    "Allergy and Immunology",
                    "Infectious Diseases",
                    "Immunizations and Vaccinations",
                    "Geriatric Care",
                    "Palliative Care",
                    "Hospice Care",
                    "Pain Management",
                    "Sleep Medicine",
                    "Wound Care",
                    "Telemedicine",
                    "Diagnostic Services",
                    "Medical Imaging (X-ray, MRI, CT Scan)",
                    "Laboratory Testing",
                    "Blood Transfusions",
                    "IV Therapy",
                    "Nutrition and Dietetics",
                    "Lifestyle Counseling",
                    "Smoking Cessation Support",
                    "Weight Management",
                    "Diabetes Management",
                    "Heart Health Monitoring",
                    "Respiratory Therapy",
                    "Health Screenings",
                    "Genetic Counseling"
                ],
            "painting":
                [
                    "Acrylic Painting",
                    "Oil Painting",
                    "Watercolor Painting",
                    "Digital Painting",
                    "Fresco Painting",
                    "Spray Painting",
                    "Encaustic Painting",
                    "Tempera Painting",
                    "Gouache Painting",
                    "Ink Painting",
                    "Canvas Painting",
                    "Landscape Painting",
                    "Portrait Painting",
                    "Still Life Painting",
                    "Abstract Painting",
                    "Impressionist Painting",
                    "Expressionist Painting",
                    "Realism in Painting",
                    "Surrealism in Painting",
                    "Cubism in Painting",
                    "Pointillism",
                    "Minimalist Painting",
                    "Fantasy Art",
                    "Modern Art",
                    "Contemporary Art",
                    "Pop Art",
                    "Street Art",
                    "Mixed Media Art",
                    "Texture Techniques",
                    "Brush Techniques",
                    "Color Theory",
                    "Layering Techniques",
                    "Blending Techniques",
                    "Shading Techniques",
                    "Perspective in Painting",
                    "Composition in Art",
                    "Chiaroscuro Techniques",
                    "Imitating Light and Shadow",
                    "Figure Drawing",
                    "Floral Painting",
                    "Animal Painting",
                    "Marine and Seascape Painting",
                    "Urban Painting",
                    "Palette Knife Painting",
                    "Monochromatic Painting",
                    "Collage Art",
                    "Imaginative Painting",
                    "Cultural and Ethnic Art",
                    "Geometric Patterns",
                    "Symbolism in Art",
                    "Art Restoration",
                    "Varnishing and Sealing Paintings",
                    "Framing and Displaying Art",
                    "Art Critique and Interpretation",
                    "Art Supplies and Materials",
                    "Art History"
                ],
            "physics":
                [
                    "Classical Mechanics",
                    "Newton's Laws of Motion",
                    "Kinematics",
                    "Dynamics",
                    "Work, Energy, and Power",
                    "Conservation of Energy",
                    "Momentum and Impulse",
                    "Rotational Motion",
                    "Gravitation",
                    "Fluid Mechanics",
                    "Elasticity",
                    "Oscillations",
                    "Simple Harmonic Motion (SHM)",
                    "Waves and Sound",
                    "Thermodynamics",
                    "Heat and Temperature",
                    "Laws of Thermodynamics",
                    "Kinetic Theory of Gases",
                    "Thermal Expansion",
                    "Entropy",
                    "Electromagnetism",
                    "Electric Charge and Electric Field",
                    "Gauss's Law",
                    "Electric Potential and Voltage",
                    "Capacitance and Dielectrics",
                    "Current Electricity",
                    "Ohm's Law",
                    "Kirchhoff's Laws",
                    "Magnetism",
                    "Ampere’s Law",
                    "Faraday’s Law of Electromagnetic Induction",
                    "Lenz’s Law",
                    "AC and DC Circuits",
                    "Electromagnetic Waves",
                    "Optics",
                    "Reflection and Refraction of Light",
                    "Lenses and Mirrors",
                    "Wave Optics",
                    "Interference and Diffraction",
                    "Polarization",
                    "Modern Physics",
                    "Photoelectric Effect",
                    "Wave-Particle Duality",
                    "Atomic Models",
                    "Nuclear Physics",
                    "Radioactivity",
                    "Nuclear Fission and Fusion",
                    "Quantum Mechanics",
                    "Schrodinger Equation",
                    "Heisenberg’s Uncertainty Principle",
                    "Relativity",
                    "Special Relativity",
                    "General Relativity",
                    "Cosmology",
                    "Big Bang Theory",
                    "Dark Matter and Dark Energy",
                    "Astrophysics",
                    "Stellar Evolution",
                    "Black Holes",
                    "Particle Physics",
                    "Standard Model",
                    "Fundamental Forces",
                    "Higgs Boson",
                    "Solid State Physics",
                    "Superconductivity",
                    "Thermal Conductivity",
                    "Fluid Dynamics",
                    "Plasma Physics",
                    "Acoustics",
                    "Geophysics",
                    "Biophysics",
                    "Environmental Physics",
                    "Medical Physics",
                    "Nanophysics",
                    "Computational Physics",
                    "Statistical Mechanics"
                ],
            "chemistry":
                [
                    "Atomic Structure",
                    "Electronic Configuration",
                    "Periodic Table",
                    "Periodic Trends",
                    "Chemical Bonding",
                    "Ionic Bonding",
                    "Covalent Bonding",
                    "Metallic Bonding",
                    "Hybridization",
                    "Molecular Geometry (VSEPR Theory)",
                    "Intermolecular Forces",
                    "States of Matter",
                    "Gases and Gas Laws",
                    "Liquids and Solids",
                    "Solutions and Concentrations",
                    "Acids, Bases, and pH",
                    "Strong and Weak Acids/Bases",
                    "Buffers",
                    "Redox Reactions",
                    "Oxidation and Reduction",
                    "Stoichiometry",
                    "Mole Concept",
                    "Balancing Chemical Equations",
                    "Limiting Reactants",
                    "Thermochemistry",
                    "Enthalpy",
                    "Entropy",
                    "Gibbs Free Energy",
                    "Chemical Kinetics",
                    "Reaction Rates",
                    "Rate Laws and Reaction Order",
                    "Activation Energy",
                    "Catalysts",
                    "Chemical Equilibrium",
                    "Le Chatelier's Principle",
                    "Equilibrium Constants (Kc, Kp)",
                    "Electrochemistry",
                    "Electrochemical Cells",
                    "Galvanic and Electrolytic Cells",
                    "Standard Electrode Potentials",
                    "Nernst Equation",
                    "Organic Chemistry",
                    "Hydrocarbons (Alkanes, Alkenes, Alkynes)",
                    "Aromatic Compounds",
                    "Alcohols and Phenols",
                    "Ethers",
                    "Aldehydes and Ketones",
                    "Carboxylic Acids",
                    "Amines and Amides",
                    "Esters",
                    "Haloalkanes and Haloarenes",
                    "Polymers",
                    "Isomerism (Structural and Stereoisomerism)",
                    "Reaction Mechanisms",
                    "Substitution Reactions",
                    "Addition Reactions",
                    "Elimination Reactions",
                    "Condensation Reactions",
                    "Carbocation and Free Radical Intermediates",
                    "Inorganic Chemistry",
                    "Coordination Compounds",
                    "Crystal Field Theory",
                    "Ligands and Chelates",
                    "d-Block Elements",
                    "f-Block Elements",
                    "Transition Metals",
                    "Metallurgy",
                    "Extraction and Refining of Metals",
                    "Nuclear Chemistry",
                    "Radioactivity",
                    "Nuclear Fission and Fusion",
                    "Radiocarbon Dating",
                    "Environmental Chemistry",
                    "Pollution and Green Chemistry",
                    "Water Treatment",
                    "Air Quality and Atmospheric Chemistry",
                    "Biochemistry",
                    "Proteins and Enzymes",
                    "Carbohydrates",
                    "Lipids",
                    "Nucleic Acids (DNA/RNA)",
                    "Pharmaceutical Chemistry",
                    "Medicinal Compounds",
                    "Analytical Chemistry",
                    "Qualitative and Quantitative Analysis",
                    "Spectroscopy (UV, IR, NMR, Mass Spectrometry)",
                    "Chromatography",
                    "Titrations",
                    "Molecular Orbital Theory",
                    "Chemical Safety and Laboratory Techniques"
                ],
            "biology":
                [
                    "Cell Biology",
                    "Cell Structure and Function",
                    "Cell Organelles",
                    "Cell Membrane and Transport",
                    "Mitosis and Meiosis",
                    "Cell Cycle and Regulation",
                    "Genetics",
                    "Mendelian Genetics",
                    "Non-Mendelian Inheritance",
                    "DNA Structure and Replication",
                    "RNA and Transcription",
                    "Protein Synthesis (Translation)",
                    "Genetic Mutations",
                    "Genetic Engineering",
                    "Recombinant DNA Technology",
                    "CRISPR Technology",
                    "Evolution and Natural Selection",
                    "Darwin’s Theory of Evolution",
                    "Speciation",
                    "Adaptation",
                    "Evidence of Evolution",
                    "Population Genetics",
                    "Ecology",
                    "Ecosystem Structure and Function",
                    "Food Chains and Webs",
                    "Energy Flow in Ecosystems",
                    "Biogeochemical Cycles",
                    "Population Dynamics",
                    "Community Interactions",
                    "Conservation Biology",
                    "Biodiversity",
                    "Biomes",
                    "Animal Physiology",
                    "Nervous System",
                    "Endocrine System",
                    "Circulatory System",
                    "Respiratory System",
                    "Digestive System",
                    "Excretory System",
                    "Skeletal and Muscular System",
                    "Immune System",
                    "Reproductive System",
                    "Plant Biology",
                    "Plant Structure and Function",
                    "Photosynthesis",
                    "Plant Hormones",
                    "Transport in Plants",
                    "Reproduction in Plants",
                    "Plant Adaptations",
                    "Microbiology",
                    "Bacteria",
                    "Viruses",
                    "Fungi",
                    "Protists",
                    "Archaea",
                    "Immunology",
                    "Innate Immunity",
                    "Adaptive Immunity",
                    "Antibodies and Antigens",
                    "Vaccines",
                    "Human Health and Disease",
                    "Infectious Diseases",
                    "Non-Communicable Diseases",
                    "Nutrition and Diet",
                    "Endocrine Disorders",
                    "Genetic Disorders",
                    "Biotechnology",
                    "Cloning",
                    "Stem Cell Research",
                    "Bioremediation",
                    "Synthetic Biology",
                    "Behavioral Biology",
                    "Animal Behavior",
                    "Social Behavior",
                    "Communication in Animals",
                    "Hormonal Control of Behavior",
                    "Developmental Biology",
                    "Embryonic Development",
                    "Cell Differentiation",
                    "Morphogenesis",
                    "Regeneration",
                    "Bioenergetics",
                    "ATP and Energy Transfer",
                    "Cellular Respiration",
                    "Fermentation",
                    "Systems Biology",
                    "Omics Technologies (Genomics, Proteomics, Metabolomics)",
                    "Human Genome Project",
                    "Evolutionary Developmental Biology (Evo-Devo)",
                    "Environmental Biology",
                    "Pollution and Its Effects",
                    "Climate Change and Biology",
                    "Endangered Species",
                    "Marine Biology",
                    "Aquatic Ecosystems",
                    "Photosynthetic Organisms in Marine Environments"
                ],
            "computer_science":
                [
                    "Programming Fundamentals",
                    "C Programming",
                    "C++ Programming",
                    "Java Programming",
                    "Python Programming",
                    "Data Structures and Algorithms",
                    "Arrays",
                    "Linked Lists",
                    "Stacks and Queues",
                    "Trees and Graphs",
                    "Sorting and Searching Algorithms",
                    "Hashing",
                    "Dynamic Programming",
                    "Object-Oriented Programming (OOP)",
                    "Classes and Objects",
                    "Inheritance",
                    "Polymorphism",
                    "Abstraction",
                    "Encapsulation",
                    "Operating Systems",
                    "Process Management",
                    "Memory Management",
                    "File Systems",
                    "Deadlocks",
                    "Scheduling Algorithms",
                    "Virtual Memory",
                    "Computer Networks",
                    "Network Protocols",
                    "OSI and TCP/IP Models",
                    "IP Addressing and Subnetting",
                    "Routing and Switching",
                    "Wireless Networks",
                    "Network Security",
                    "Database Management Systems (DBMS)",
                    "Relational Databases",
                    "SQL",
                    "Normalization",
                    "Transactions and Concurrency Control",
                    "NoSQL Databases",
                    "Distributed Databases",
                    "Software Engineering",
                    "Software Development Life Cycle (SDLC)",
                    "Agile Methodology",
                    "Requirements Analysis",
                    "Software Design Patterns",
                    "Software Testing",
                    "Version Control (Git)",
                    "Web Development",
                    "HTML, CSS, and JavaScript",
                    "Frontend Frameworks (React, Angular, Vue.js)",
                    "Backend Development (Node.js, Django, Flask)",
                    "APIs and RESTful Services",
                    "Full-Stack Development",
                    "Cloud Computing",
                    "Virtualization",
                    "Cloud Service Models (IaaS, PaaS, SaaS)",
                    "AWS, Azure, and Google Cloud",
                    "DevOps and Continuous Integration/Continuous Deployment (CI/CD)",
                    "Artificial Intelligence (AI)",
                    "Machine Learning (ML)",
                    "Deep Learning",
                    "Neural Networks",
                    "Natural Language Processing (NLP)",
                    "Computer Vision",
                    "Reinforcement Learning",
                    "Data Science",
                    "Data Preprocessing and Cleaning",
                    "Data Visualization",
                    "Statistical Analysis",
                    "Big Data (Hadoop, Spark)",
                    "Internet of Things (IoT)",
                    "IoT Architecture",
                    "IoT Communication Protocols",
                    "Edge and Fog Computing",
                    "Cybersecurity",
                    "Cryptography",
                    "Firewalls and Intrusion Detection",
                    "Ethical Hacking",
                    "Cyber Threats and Vulnerabilities",
                    "Blockchain",
                    "Consensus Mechanisms",
                    "Smart Contracts",
                    "Decentralized Applications (DApps)",
                    "Compiler Design",
                    "Lexical Analysis",
                    "Syntax Analysis",
                    "Code Generation and Optimization",
                    "Theory of Computation",
                    "Finite Automata",
                    "Regular Expressions",
                    "Context-Free Grammars",
                    "Turing Machines",
                    "Artificial Intelligence Search Algorithms",
                    "Data Mining",
                    "Software Project Management",
                    "Embedded Systems",
                    "Microprocessors and Microcontrollers",
                    "Human-Computer Interaction (HCI)",
                    "Parallel and Distributed Computing",
                    "Quantum Computing (Introductory Concepts)",
                    "Mobile Application Development",
                    "Android Development",
                    "iOS Development",
                    "Game Development",
                    "Augmented Reality (AR) and Virtual Reality (VR)"
                ],
            "electronics":
                [
                    "Basic Electronics",
                    "Resistors, Capacitors, Inductors",
                    "Diodes and Rectifiers",
                    "Transistors (BJT, FET, MOSFET)",
                    "Operational Amplifiers (Op-Amps)",
                    "Analog Electronics",
                    "Amplifiers",
                    "Oscillators",
                    "Filters (Low-pass, High-pass, Band-pass)",
                    "Feedback Systems",
                    "Power Electronics",
                    "DC-DC Converters",
                    "Inverters",
                    "AC Voltage Controllers",
                    "Rectifiers and Cycloconverters",
                    "Semiconductor Devices",
                    "PN Junction Diodes",
                    "Zener Diodes",
                    "Light Emitting Diodes (LEDs)",
                    "Photodiodes",
                    "Microprocessors and Microcontrollers",
                    "8085 Microprocessor",
                    "8086 Microprocessor",
                    "PIC Microcontrollers",
                    "ARM Processors",
                    "Embedded Systems",
                    "Real-Time Operating Systems (RTOS)",
                    "Interfacing Techniques",
                    "Sensors and Actuators",
                    "Digital Electronics",
                    "Logic Gates",
                    "Combinational Circuits",
                    "Sequential Circuits",
                    "Flip-Flops",
                    "Counters and Registers",
                    "Multiplexers and Demultiplexers",
                    "Analog-to-Digital Converters (ADC)",
                    "Digital-to-Analog Converters (DAC)",
                    "VLSI Design",
                    "MOSFET Fabrication",
                    "CMOS Technology",
                    "Digital System Design",
                    "FPGA and ASIC Design",
                    "Signal Processing",
                    "Fourier Transform",
                    "Z-Transform",
                    "Digital Signal Processing (DSP)",
                    "Filters (IIR, FIR)",
                    "Image Processing",
                    "Communication Systems",
                    "Amplitude Modulation (AM)",
                    "Frequency Modulation (FM)",
                    "Phase Modulation (PM)",
                    "Pulse Modulation Techniques",
                    "Digital Communication",
                    "Information Theory and Coding",
                    "Error Detection and Correction",
                    "Wireless Communication",
                    "Satellite Communication",
                    "Optical Communication",
                    "Microwave Engineering",
                    "Microwave Waveguides",
                    "Microwave Antennas",
                    "Radar Systems",
                    "Antenna Theory",
                    "Electromagnetic Waves",
                    "Transmission Lines",
                    "Wave Propagation",
                    "Electromagnetic Interference (EMI) and Compatibility (EMC)",
                    "Control Systems",
                    "Open-Loop and Closed-Loop Control",
                    "Transfer Functions",
                    "Stability Analysis",
                    "PID Controllers",
                    "State-Space Analysis",
                    "Instrumentation and Measurement",
                    "Transducers",
                    "Data Acquisition Systems",
                    "Signal Conditioning",
                    "Biomedical Instrumentation",
                    "Wireless Sensor Networks (WSN)",
                    "Internet of Things (IoT)",
                    "Robotics",
                    "Industrial Automation",
                    "Automation using PLCs",
                    "Mechatronics",
                    "Artificial Intelligence in Electronics",
                    "Renewable Energy Systems",
                    "Solar and Wind Energy Electronics",
                    "Smart Grid Technology",
                    "Nanotechnology in Electronics",
                    "Quantum Electronics",
                    "Nanoelectronics"
                ],
            "geography":
                [
                    "Physical Geography",
                    "Geomorphology",
                    "Plate Tectonics and Continental Drift",
                    "Earthquakes and Volcanoes",
                    "Weathering and Erosion",
                    "Mountains, Valleys, and Plains",
                    "Rivers and Drainage Systems",
                    "Glaciers and Glaciation",
                    "Deserts and Arid Landscapes",
                    "Oceans and Seas",
                    "Climate and Weather",
                    "Atmospheric Pressure and Wind Systems",
                    "Cyclones and Anticyclones",
                    "Monsoons",
                    "El Niño and La Niña",
                    "Climatic Zones and Biomes",
                    "Hydrology and the Water Cycle",
                    "Ocean Currents",
                    "Tides and Waves",
                    "Human Geography",
                    "Population Geography",
                    "Migration Patterns",
                    "Urbanization and Cities",
                    "Rural Settlement Patterns",
                    "Demographic Transition Model",
                    "Cultural Geography",
                    "Languages and Religions",
                    "Ethnicity and Identity",
                    "Economic Geography",
                    "Agriculture and Farming Systems",
                    "Industry and Manufacturing",
                    "Trade and Transportation",
                    "Tourism Geography",
                    "Development and Globalization",
                    "Political Geography",
                    "Geopolitics and Boundaries",
                    "Nation-States and Territories",
                    "Colonialism and Imperialism",
                    "Global Conflicts and Alliances",
                    "Environmental Geography",
                    "Sustainable Development",
                    "Deforestation and Desertification",
                    "Pollution and Environmental Hazards",
                    "Climate Change and Global Warming",
                    "Conservation of Biodiversity",
                    "Natural Disasters and Risk Management",
                    "Soil Geography",
                    "Soil Formation and Classification",
                    "Soil Erosion and Conservation",
                    "Biogeography",
                    "Ecosystems and Habitats",
                    "Flora and Fauna Distribution",
                    "Ecological Succession",
                    "Cartography and Geographic Information Systems (GIS)",
                    "Map Projections and Scale",
                    "Thematic and Topographic Maps",
                    "Remote Sensing",
                    "Spatial Analysis",
                    "Geostatistics",
                    "World Geography",
                    "Continents and Oceans",
                    "Countries and Capitals",
                    "Major Rivers and Lakes",
                    "Mountain Ranges and Deserts",
                    "Cultural Regions",
                    "Economic and Political Regions",
                    "Urban Geography",
                    "City Structures and Land Use",
                    "Urban Planning and Development",
                    "Smart Cities",
                    "Transport Geography",
                    "Modes of Transportation",
                    "Transport Networks",
                    "Global Trade Routes",
                    "Health Geography",
                    "Epidemiology and Disease Patterns",
                    "Healthcare Access and Inequality",
                    "Environmental Determinants of Health",
                    "Historical Geography",
                    "Ancient Civilizations and Empires",
                    "Colonial and Post-Colonial Geography",
                    "Geography of Religion",
                    "Sacred Spaces and Pilgrimage",
                    "Religion and Cultural Landscapes"
                ],
            "political_science":
                [
                    "Political Theory",
                    "Classical Political Philosophy",
                    "Modern Political Philosophy",
                    "Social Contract Theory",
                    "Utilitarianism",
                    "Marxism and Communism",
                    "Liberalism",
                    "Conservatism",
                    "Socialism",
                    "Feminist Political Theory",
                    "Postcolonial Theory",
                    "Democratic Theory",
                    "Citizenship and Political Participation",
                    "Power, Authority, and Legitimacy",
                    "State and Sovereignty",
                    "Rights and Liberties",
                    "Justice and Equality",
                    "Law and Morality",
                    "Comparative Politics",
                    "Political Systems and Regimes",
                    "Democracies and Dictatorships",
                    "Presidential and Parliamentary Systems",
                    "Federalism and Unitarianism",
                    "Electoral Systems",
                    "Political Parties and Party Systems",
                    "Interest Groups and Lobbying",
                    "Social Movements and Political Change",
                    "Political Culture and Socialization",
                    "Political Institutions and Governance",
                    "Constitutional Design and Judicial Review",
                    "Executive and Legislative Relations",
                    "Civil-Military Relations",
                    "Public Administration and Bureaucracy",
                    "Local Government and Decentralization",
                    "International Relations",
                    "Theories of International Relations",
                    "Realism and Neorealism",
                    "Liberalism and Neoliberalism",
                    "Constructivism",
                    "Feminism in International Relations",
                    "Critical Theory",
                    "International Organizations and Global Governance",
                    "United Nations and its Agencies",
                    "World Trade Organization (WTO)",
                    "International Monetary Fund (IMF)",
                    "International Law and Human Rights",
                    "Diplomacy and Foreign Policy",
                    "Global Security and Peace Studies",
                    "Nuclear Proliferation and Disarmament",
                    "Conflict Resolution and Peacebuilding",
                    "Terrorism and Counterterrorism",
                    "Environmental Politics and Global Climate Change",
                    "Development and Global Inequality",
                    "Political Economy",
                    "Capitalism and Globalization",
                    "Economic Development and Political Change",
                    "Welfare State and Social Policy",
                    "Public Choice Theory",
                    "Political Ideologies and Economic Systems",
                    "Political Psychology",
                    "Political Behavior and Public Opinion",
                    "Identity Politics and Nationalism",
                    "Ethnic Conflict and Genocide",
                    "Religion and Politics",
                    "Gender and Politics",
                    "Race and Ethnicity in Politics",
                    "Political Leadership",
                    "Populism and Authoritarianism",
                    "Political Corruption and Accountability",
                    "Human Rights and Civil Liberties",
                    "Electoral Behavior and Voting Patterns",
                    "Media and Politics",
                    "Political Communication and Propaganda",
                    "Campaign Strategies and Elections",
                    "Cyber Politics and Digital Democracy",
                    "Constitutional Law",
                    "Separation of Powers",
                    "Checks and Balances",
                    "Judicial Activism and Restraint",
                    "Rule of Law",
                    "Globalization and its Political Impact",
                    "Regionalism and Regional Integration",
                    "Nationalism and Secession Movements"
                ],
            "authors":
                [
                    # 1980s
                    ("Gabriel García Márquez", "Love in the Time of Cholera (1985)"),
                    ("Margaret Atwood", "The Handmaid’s Tale (1985)"),
                    ("Toni Morrison", "Beloved (1987)"),
                    ("Kazuo Ishiguro", "The Remains of the Day (1989)"),
                    ("Stephen King", "It (1986)"),
                    ("Salman Rushdie", "The Satanic Verses (1988)"),
                    ("Tom Clancy", "The Hunt for Red October (1984)"),
                    ("Isabel Allende", "Of Love and Shadows (1985)"),
                    ("Jeanette Winterson", "Oranges Are Not the Only Fruit (1985)"),
                    ("Umberto Eco", "Foucault’s Pendulum (1988)"),
                    
                    # 1990s
                    ("Haruki Murakami", "Norwegian Wood (1987, English Translation 2000)"),
                    ("Michael Crichton", "Jurassic Park (1990)"),
                    ("Donna Tartt", "The Secret History (1992)"),
                    ("John Grisham", "The Firm (1991)"),
                    ("Terry Pratchett and Neil Gaiman", "Good Omens (1990)"),
                    ("Philip Pullman", "The Golden Compass (1995)"),
                    ("J.K. Rowling", "Harry Potter and the Philosopher’s Stone (1997)"),
                    ("Arundhati Roy", "The God of Small Things (1997)"),
                    ("Kurt Vonnegut", "Timequake (1997)"),
                    ("Terry Pratchett", "Hogfather (1996)"),
                    ("Anne Rice", "Memnoch the Devil (1995)"),
                    ("Chuck Palahniuk", "Fight Club (1996)"),
                    ("Alice Munro", "Open Secrets (1994)"),
                    ("Nick Hornby", "High Fidelity (1995)"),

                    # 2000s
                    ("Khaled Hosseini", "The Kite Runner (2003)"),
                    ("Dan Brown", "The Da Vinci Code (2003)"),
                    ("Markus Zusak", "The Book Thief (2005)"),
                    ("Cormac McCarthy", "The Road (2006)"),
                    ("Stieg Larsson", "The Girl with the Dragon Tattoo (2005)"),
                    ("Stephenie Meyer", "Twilight (2005)"),
                    ("Chimamanda Ngozi Adichie", "Half of a Yellow Sun (2006)"),
                    ("Suzanne Collins", "The Hunger Games (2008)"),
                    ("Jhumpa Lahiri", "The Namesake (2003)"),
                    ("Jonathan Safran Foer", "Extremely Loud & Incredibly Close (2005)"),
                    ("Kiran Desai", "The Inheritance of Loss (2006)"),
                    ("Ian McEwan", "Atonement (2001)"),
                    ("Orhan Pamuk", "Snow (2004)"),
                    ("Gillian Flynn", "Gone Girl (2012)"),

                    # 2010s
                    ("E.L. James", "Fifty Shades of Grey (2011)"),
                    ("Anthony Doerr", "All the Light We Cannot See (2014)"),
                    ("Paula Hawkins", "The Girl on the Train (2015)"),
                    ("Colson Whitehead", "The Underground Railroad (2016)"),
                    ("Margaret Atwood", "The Testaments (2019)"),
                    ("Delia Owens", "Where the Crawdads Sing (2018)"),
                    ("Michelle Obama", "Becoming (2018)"),
                    ("Sally Rooney", "Normal People (2018)"),
                    ("Rupi Kaur", "Milk and Honey (2014)"),
                    ("George Saunders", "Lincoln in the Bardo (2017)"),
                    ("Tomi Adeyemi", "Children of Blood and Bone (2018)"),
                    ("Han Kang", "The Vegetarian (2016, English translation)"),
                    ("Emily St. John Mandel", "Station Eleven (2014)"),
                    ("Angie Thomas", "The Hate U Give (2017)"),

                    # 2020s
                    ("Taylor Jenkins Reid", "The Seven Husbands of Evelyn Hugo (2017, popularity peaked in 2020s)"),
                    ("Madeline Miller", "Circe (2018, remained popular through the 2020s)"),
                    ("Brit Bennett", "The Vanishing Half (2020)"),
                    ("Kazuo Ishiguro", "Klara and the Sun (2021)"),
                    ("Colleen Hoover", "It Ends With Us (2016, gained massive popularity in 2020s)"),
                    ("Emily St. John Mandel", "Sea of Tranquility (2022)"),
                    ("Bonnie Garmus", "Lessons in Chemistry (2022)"),
                    ("Jean Hanff Korelitz", "The Plot (2021)"),
                    ("T.J. Klune", "The House in the Cerulean Sea (2020)"),
                    ("Douglas Stuart", "Shuggie Bain (2020)"),
                    ("Abigail Dean", "Girl A (2021)"),
                    ("Ali Hazelwood", "The Love Hypothesis (2021)"),
                    ("Nita Prose", "The Maid (2022)"),
                    ("Rebecca Yarros", "Fourth Wing (2023)"),

                    # Prizes
                    ("Gabriel García Márquez", "Nobel Prize in Literature (1982)"),
                    ("Kazuo Ishiguro", "Nobel Prize in Literature (2017)"),
                    ("Toni Morrison", "Nobel Prize in Literature (1993)"),
                    ("Margaret Atwood", "Booker Prize (2000, 2019)"),
                    ("Salman Rushdie", "Booker Prize (1981)"),
                    ("J.M. Coetzee", "Nobel Prize in Literature (2003), Booker Prize (1983, 1999)"),
                    ("Orhan Pamuk", "Nobel Prize in Literature (2006)"),
                    ("Patrick Modiano", "Nobel Prize in Literature (2014)"),
                    ("Alice Munro", "Nobel Prize in Literature (2013)"),
                    ("Jean-Marie Gustave Le Clézio", "Nobel Prize in Literature (2008)"),
                    ("Haruki Murakami", "Jerusalem Prize (2009)"),
                    ("Chimamanda Ngozi Adichie", "Women’s Prize for Fiction (2007)"),
                    ("Colson Whitehead", "Pulitzer Prize for Fiction (2017, 2020)"),
                    ("George Saunders", "Booker Prize (2017)"),
                    ("Hilary Mantel", "Booker Prize (2009, 2012)"),
                    ("Anne Enright", "Booker Prize (2007)"),
                    ("Michael Ondaatje", "Booker Prize (1992)"),
                    ("Bernardine Evaristo", "Booker Prize (2019)"),
                    ("Olga Tokarczuk", "Nobel Prize in Literature (2018)"),
                    ("Ishmael Reed", "MacArthur Fellowship (1998)"),
                    ("Marilynne Robinson", "Pulitzer Prize for Fiction (2005)"),
                    ("Richard Powers", "Pulitzer Prize for Fiction (2019)"),
                    ("Tayari Jones", "Women’s Prize for Fiction (2019)"),
                    ("Sally Rooney", "Costa Novel Award (2018)"),
                    ("Donna Tartt", "Pulitzer Prize for Fiction (2014)"),
                    ("Jhumpa Lahiri", "Pulitzer Prize for Fiction (2000)"),
                    ("Annie Ernaux", "Nobel Prize in Literature (2022)"),
                    ("Anita Desai", "Man Booker Prize Finalist (1980, 1984, 1999)"),
                    ("Isabel Allende", "Presidential Medal of Freedom (2014)"),
                    ("Kiran Desai", "Booker Prize (2006)"),
                    ("Arundhati Roy", "Booker Prize (1997)"),
                    ("Elizabeth Strout", "Pulitzer Prize for Fiction (2009)"),
                    ("Eleanor Catton", "Booker Prize (2013)"),
                    ("Douglas Stuart", "Booker Prize (2020)"),
                    ("Han Kang", "Man Booker International Prize (2016)"),
                    ("Julian Barnes", "Booker Prize (2011)"),
                    ("Damon Galgut", "Booker Prize (2021)"),
                    ("Elena Ferrante", "TIME 100 Most Influential People (2016)"),
                    ("Anthony Doerr", "Pulitzer Prize for Fiction (2015)"),
                    ("Kazuo Ishiguro", "Booker Prize (1989)"),
                    ("Marieke Lucas Rijneveld", "International Booker Prize (2020)"),
                    ("Tayeb Salih", "Cultural Personality of the Year (2005)"),
                    ("Benjamin Black (John Banville)", "Booker Prize (2005)"),
                    ("Anne Carson", "Princess of Asturias Award (2020)"),
                    ("Hanif Kureishi", "Chevalier de l'Ordre des Arts et des Lettres (2001)"),
                    ("Bernard Malamud", "Pulitzer Prize for Fiction (1967)")
                ]
            }

        self.json_store = JsonDataStore(self.section_json_root_map[self.section])
        self.gcs_json_file = f"{self.section}.json"

        self.gcs_manager = GCSManager("kupmanduk-bucket", constants.GCS_ROOT_FOLDER)

        self.google_cse_access = GoogleCSEAccess(self.error_manager)
        self.google_cse_access.initialize()

        self.init()

    def init(self):
        if self.gcs_manager.is_exist(self.gcs_json_file):
            d = self.gcs_manager.read_json(self.gcs_json_file)
            self.json_store.update_from_json_data(d)

    def get_random_topic(self):
        topics = self.topic_list[self.section]
        return self.normalize_topic(random.choice(topics))

    def get_content_for_topic(self, topic):
        content = self.json_store.read_key(topic)

        return content

    def generate_content(self, topic):
        content = self.get_content_for_topic(topic)
        if not content:
            content = self.generate_content_implementation(topic)
            self.json_store.save_key(topic, content)

    # The topic may have complex set of items seperated by 
    # commas - such as in 'authors'
    def normalize_topic(self, topic):
        if isinstance(topic, tuple):  # If the item is a tuple, concatenate the elements
            concatenated_string = " ".join(topic)
        else:  # If the item is a simple string, keep it as it is
            concatenated_string = topic

        return concatenated_string

    def generate_all_contents(self):
        topics = self.topic_list[self.section]
        for t in topics:
            t = self.normalize_topic(t)
            print(f"Generating content for topic {t}")
            self.generate_content(t)

    def generate_content_implementation(self, topic):
        response = self.gemini_access.generate_content(self.section, topic)
        return response

    def finish(self):
        self.gcs_manager.write_json(self.gcs_json_file, self.json_store.get_json_data())

    def generate_youtube_response(self, topic):
        search_line = f"youtube {self.section} {topic}"
        search_line = search_line.replace('_', ' ')
        response = self.google_cse_access.search(search_line)
        return response


