#!/bin/bash

# export GOOGLE_API_KEY=AIzaSyAQCZ2bJHOI6yapnei35Eyrd2IL19ts9GM
export GOOGLE_API_KEY=
export GOOGLE_CSE_API_KEY=

export GOOGLE_APPLICATION_CREDENTIALS="kupmanduk_GCS_signed_URL_key.json"

export GOOGLE_CSE_ID="86bcdaa3e3cf148e8"

export RUN_SERVER_IN_LOCAL_MACHINE=t

gunicorn --workers 1 --threads 2 --timeout 300 --log-level debug --access-logfile - --error-logfile -  flask_file_accept:app

# python flask_file_accept.py



