#!/bin/bash

# export GOOGLE_API_KEY=AIzaSyAQCZ2bJHOI6yapnei35Eyrd2IL19ts9GM
export GOOGLE_API_KEY=AIzaSyDJDcvSAXCnz3sQaj1_cFWj2JY_hmrW0-g

export GOOGLE_APPLICATION_CREDENTIALS="kupmanduk_GCS_signed_URL_key.json"

export GOOGLE_CSE_ID="86bcdaa3e3cf148e8"

export RUN_SERVER_IN_LOCAL_MACHINE=t

gunicorn -w 4 --timeout 300 -k gevent flask_file_accept:app

# python flask_file_accept.py



